# -*- coding: utf-8 -*-
"""Music Genre Classifier.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1FsfntdWuONYguxOWFxFQagTscNuFp8hK
"""

!pip install scikit-learn pandas matplotlib seaborn

import pandas as pd
file_path = '/content/drive/MyDrive/Datasets/features_30_sec.csv'
df = pd.read_csv(file_path)
df.head()

df.isnull().sum()

X = df.drop(['filename','label'], axis=1)
  y = df['label']

from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
X_scaled = scaler.fit_transform(X)

from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X_scaled, y, test_size=0.2, random_state=42)

print(X_train.shape, X_test.shape)

from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score, classification_report

model  = RandomForestClassifier(n_estimators=100, random_state=42)
model.fit(X_train, y_train)

y_pred = model.predict(X_test)

accuracy = accuracy_score(y_test, y_pred)
print(f'Accuracy: {accuracy}')
print(classification_report(y_test, y_pred))

from google.colab import files
files.download('')